# Generated by Django 4.0.3 on 2022-03-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descprtion',
            new_name='description',
        ),
    ]
