# Generated by Django 4.0.3 on 2022-03-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_descprtion_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
